// Generated by CoffeeScript 1.8.0
(function() {
  module.exports = {
    Myo: require('./lib/myo'),
    Pose: require('./lib/pose'),
    Vector3: require('./lib/vector3'),
    Quaternion: require('./lib/quaternion'),
    Arm: require('./lib/arm')
  };

}).call(this);
