// Generated by CoffeeScript 1.8.0
(function() {
  var Command;

  Command = {
    getSetModeCommand: function(emgMode, imuMode, classifierMode) {
      var SETMODE_SIZE, command;
      SETMODE_SIZE = 5;
      command = new Buffer(SETMODE_SIZE);
      command.writeUInt8(1, 0);
      command.writeUInt8(SETMODE_SIZE - 2, 1);
      command.writeUInt8(emgMode, 2);
      command.writeUInt8(imuMode, 3);
      command.writeUInt8(classifierMode, 4);
      return command;
    },
    getVibrateCommand: function(duration) {
      var VIBRATE_SIZE, command;
      VIBRATE_SIZE = 3;
      command = new Buffer(VIBRATE_SIZE);
      command.writeUInt8(3, 0);
      command.writeUInt8(VIBRATE_SIZE - 2, 1);
      command.writeUInt8(duration, 2);
      return command;
    },
    getUnlockCommand: function(type) {
      var UNLOCK_SIZE, command;
      UNLOCK_SIZE = 3;
      command = new Buffer(UNLOCK_SIZE);
      command.writeUInt8(10, 0);
      command.writeUInt8(UNLOCK_SIZE - 2, 1);
      command.writeUInt8(type, 2);
      return command;
    },
    getLockCommand: function() {
      var LOCK_SIZE, command;
      LOCK_SIZE = 2;
      command = new Buffer(LOCK_SIZE);
      command.writeUInt8(11, 0);
      command.writeUInt8(0, 1);
      return command;
    },
    lockPolicy: {
      NONE: 0,
      STANDARD: 1
    },
    unlock: {
      TIMED: 1,
      HOLD: 2
    },
    classifier: {
      DISABLE: 0,
      ENABLE: 1
    },
    imu: {
      DISABLE: 0,
      ENABLE: 1
    },
    emg: {
      DISABLE: 0,
      FV: 1,
      STREAM: 2
    }
  };

  module.exports = Command;

}).call(this);
