// Generated by CoffeeScript 1.8.0
(function() {
  var EventEmitter, IMU,
    __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; },
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  EventEmitter = require('events').EventEmitter;

  IMU = (function(_super) {
    __extends(IMU, _super);

    function IMU(opt) {
      this.newData = __bind(this.newData, this);
      IMU.__super__.constructor.apply(this, arguments);
    }

    IMU.prototype.newData = function(raw) {
      var acc, gyro, quat;
      quat = raw.slice(0, 8);
      acc = raw.slice(8, 14);
      gyro = raw.slice(14, 20);
      return this.emit('data', [quat, acc, gyro]);
    };

    return IMU;

  })(EventEmitter);

  module.exports = IMU;

}).call(this);
