// Generated by CoffeeScript 1.8.0
(function() {
  var Pose;

  Pose = (function() {
    Pose.prototype._pStringMapping = {
      0: 'rest',
      1: 'fist',
      2: 'wave_in',
      3: 'wave_out',
      4: 'finger_spread',
      5: 'thumb_to_pinky'
    };

    function Pose(pose) {
      this.pose = pose;
    }

    Pose.prototype.toString = function() {
      return this._pStringMapping[this.pose];
    };

    return Pose;

  })();

  Pose.Pose = {
    REST: 0,
    FIST: 1,
    WAVE_IN: 2,
    WAVE_OUT: 3,
    FINGER_SPREAD: 4,
    THUMB_TO_PINKY: 5,
    UNKNOWN: 255
  };

  module.exports = Pose;

}).call(this);
