// Generated by CoffeeScript 1.8.0
(function() {
  var Vector3;

  Vector3 = {
    parse: function(buf, scale) {
      return [buf.readInt16LE(0) / scale, buf.readInt16LE(2) / scale, buf.readInt16LE(4) / scale];
    }
  };

  Vector3.ACCEL = 2048.0;

  Vector3.GYRO = 16.0;

  module.exports = Vector3;

}).call(this);
